#!/bin/bash

# Get the Python code from the environment variable
python_code="$PYCODE"

# Check if the environment variable is set
if [ -z "$python_code" ]; then
    echo "Error: Environment variable not set."
    exit 1
fi

# Run the Python code
python3 -c "$python_code"

